name: Compile C Code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up GCC
      run: sudo apt-get install gcc make

    - name: Compile C code
      run: |
        # Ensure the file exists before compiling
        if [ ! -f "evenflow4nbu.c" ]; then
          echo "Error: evenflow4nbu.c not found!"
          exit 1
        fi
        
        # Compile the C code
        gcc -O2 -static -pthread evenflow4nbu.c -o evenflow4nbu

    - name: Upload binary as artifact using actions/upload-artifact@v2
      uses: actions/upload-artifact@v2  # Using v2 as it's currently stable
      with:
        name: evenflow4nbu-binary
        path: evenflow4nbu
