name: Compile C Code

on:
  push:
    branches:
      - main  # This will trigger the action on push to main branch
  pull_request:
    branches:
      - main  # This will also trigger on PRs to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up GCC
      run: sudo apt-get install gcc make

    - name: Compile C code
      run: |
        gcc -O2 -static -pthread evenflow4nbu.c -o evenflow4nbu

    - name: Upload binary as artifact
      uses: actions/upload-artifact@v2
      with:
        name: evenflow4nbu-binary
        path: evenflow4nbu
